"""Add owner_id to ratings

Revision ID: 7bd4503c3da6
Revises: 9498ecdf7ed5
Create Date: 2024-07-24 00:01:11.960265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bd4503c3da6'
down_revision: Union[str, None] = '9498ecdf7ed5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
