"""Add movie_id column to comments table

Revision ID: 7c3f6d8e2052
Revises: 
Create Date: 2024-07-14 23:52:12.630561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c3f6d8e2052'
# 7c3f6d8e2052
down_revision: Union[str, None] = '35b194211194'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('movie_id', sa.Integer(), nullable=True))
    op.drop_index('ix_comments_Comment', table_name='comments')
    op.create_index(op.f('ix_comments_comment'), 'comments', ['comment'], unique=False)
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_foreign_key(None, 'comments', 'movies', ['movie_id'], ['id'])
    op.create_index(op.f('ix_ratings_rating'), 'ratings', ['rating'], unique=False)
    op.drop_index('ix_users_first_name', table_name='users')
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.drop_index('ix_users_last_name', table_name='users')
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.drop_index('ix_users_sex', table_name='users')
    op.create_index(op.f('ix_users_sex'), 'users', ['sex'], unique=False)
    op.drop_index('ix_users_user_name', table_name='users')
    op.create_index(op.f('ix_users_user_name'), 'users', ['user_name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_user_name'), table_name='users')
    op.create_index('ix_users_user_name', 'users', ['user_name'], unique=True)
    op.drop_index(op.f('ix_users_sex'), table_name='users')
    op.create_index('ix_users_sex', 'users', ['sex'], unique=True)
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.create_index('ix_users_last_name', 'users', ['last_name'], unique=True)
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.create_index('ix_users_first_name', 'users', ['first_name'], unique=True)
    op.drop_index(op.f('ix_ratings_rating'), table_name='ratings')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_comment'), table_name='comments')
    op.create_index('ix_comments_Comment', 'comments', ['comment'], unique=False)
    op.drop_column('comments', 'movie_id')
    # ### end Alembic commands ###
