"""Add owner_id to comments

Revision ID: 9498ecdf7ed5
Revises: e50fbe6904c8
Create Date: 2024-07-23 23:58:15.242100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9498ecdf7ed5'
down_revision: Union[str, None] = 'e50fbe6904c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('ratings', sa.Column('movie_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ratings', 'movies', ['movie_id'], ['id'])
    op.create_foreign_key(None, 'ratings', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.drop_column('ratings', 'movie_id')
    op.drop_column('ratings', 'owner_id')
    # ### end Alembic commands ###
