"""Add owner_id to comments

Revision ID: e50fbe6904c8
Revises: ccb4db327ca8
Create Date: 2024-07-23 23:01:44.231733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e50fbe6904c8'
down_revision: Union[str, None] = 'ccb4db327ca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'owner_id')
    # ### end Alembic commands ###
